# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Falco
tagline:          'Curiosity Coding'
description:      'Just a personal blog about Curiosity Coding'
url:              http://xfalcox.github.io

author:
  name:           'Rafael dos Santos Silva'
  url:            http://xfalcox.github.io

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/xfalcox.github.io